//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Areas.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class General {
        
        /// <summary>
        ///   Looks up a localized string similar to: Back to List
        /// </summary>
        public static string BackToList([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.BackToList;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("BackToList", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Create
        /// </summary>
        public static string Create([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.Create;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("Create", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Create of
        /// </summary>
        public static string CreateOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.CreateOf;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("CreateOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Delete
        /// </summary>
        public static string Delete([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.Delete;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("Delete", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Delete of
        /// </summary>
        public static string DeleteOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.DeleteOf;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("DeleteOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Details
        /// </summary>
        public static string Details([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.Details;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("Details", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Details of
        /// </summary>
        public static string DetailsOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.DetailsOf;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("DetailsOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Display
        /// </summary>
        public static string Display([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.Display;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("Display", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Edit
        /// </summary>
        public static string Edit([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.Edit;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("Edit", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Edit or
        /// </summary>
        public static string EditOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.EditOf;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("EditOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Get Data
        /// </summary>
        public static string GetData([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.GetData;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("GetData", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Index
        /// </summary>
        public static string Index([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.Index;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("Index", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: List of
        /// </summary>
        public static string ListOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.General.ListOf;
            }
            return global::Resources.Areas.General.ResourceManager.GetString("ListOf", resourceCulture);
        }
    }
}
namespace Resources.Areas.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class GeneralKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Back to List
        /// </summary>
        public const string BackToList = "BackToList";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Create
        /// </summary>
        public const string Create = "Create";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Create of
        /// </summary>
        public const string CreateOf = "CreateOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Delete
        /// </summary>
        public const string Delete = "Delete";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Delete of
        /// </summary>
        public const string DeleteOf = "DeleteOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Details
        /// </summary>
        public const string Details = "Details";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Details of
        /// </summary>
        public const string DetailsOf = "DetailsOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Display
        /// </summary>
        public const string Display = "Display";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Edit
        /// </summary>
        public const string Edit = "Edit";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Edit or
        /// </summary>
        public const string EditOf = "EditOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Get Data
        /// </summary>
        public const string GetData = "GetData";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Index
        /// </summary>
        public const string Index = "Index";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: List of
        /// </summary>
        public const string ListOf = "ListOf";
    }
}
