// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
	static readonly WorkflowClass s_Workflow = new WorkflowClass();
	public static WorkflowClass Workflow { get { return s_Workflow; } }
	public static MY_WEB_APPLICATION.Controllers.ErrorController Error = new MY_WEB_APPLICATION.Controllers.T4MVC_ErrorController();
	public static MainApplication.Controllers.HomeController Home = new MainApplication.Controllers.T4MVC_HomeController();
	public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public class WorkflowClass
	{
		public readonly string Name = "Workflow";
		public MainApplication.Areas.Workflow.Controllers.HomeController Home = new MainApplication.Areas.Workflow.Controllers.T4MVC_HomeController();
		public MainApplication.Areas.Workflow.Controllers.ProcessController Process = new MainApplication.Areas.Workflow.Controllers.T4MVC_ProcessController();
		public T4MVC.Workflow.SharedController Shared = new T4MVC.Workflow.SharedController();
	}
}

namespace T4MVC
{
	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public class Dummy
	{
		private Dummy() { }
		public static Dummy Instance = new Dummy();
	}
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ViewResult : System.Web.Mvc.ViewResult, IT4MVCActionResult
{
	public T4MVC_System_Web_Mvc_ViewResult(string area, string controller, string action, string protocol = null): base()
	{
		this.InitMVCT4Result(area, controller, action, protocol);
	}
	
	public string Controller { get; set; }
	public string Action { get; set; }
	public string Protocol { get; set; }
	public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
	public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
	{
		this.InitMVCT4Result(area, controller, action, protocol);
	}
	 
	public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
	
	public string Controller { get; set; }
	public string Action { get; set; }
	public string Protocol { get; set; }
	public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public static class scripts {
		public const string UrlPath = "~/scripts";
		public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
		public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
    	public static readonly string ai_0_22_19_build00125_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ai.0.22.19-build00125.min.js") ? Url("ai.0.22.19-build00125.min.js") : Url("ai.0.22.19-build00125.js");
    	public static readonly string ai_0_22_19_build00125_min_js = Url("ai.0.22.19-build00125.min.js");
    	public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
    	public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
    	public static readonly string jquery_3_1_0_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.0.intellisense.min.js") ? Url("jquery-3.1.0.intellisense.min.js") : Url("jquery-3.1.0.intellisense.js");
    	public static readonly string jquery_3_1_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.0.min.js") ? Url("jquery-3.1.0.min.js") : Url("jquery-3.1.0.js");
    	public static readonly string jquery_3_1_0_min_js = Url("jquery-3.1.0.min.js");
    	public static readonly string jquery_3_1_0_min_map = Url("jquery-3.1.0.min.map");
    	public static readonly string jquery_3_1_0_slim_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.0.slim.min.js") ? Url("jquery-3.1.0.slim.min.js") : Url("jquery-3.1.0.slim.js");
    	public static readonly string jquery_3_1_0_slim_min_js = Url("jquery-3.1.0.slim.min.js");
    	public static readonly string jquery_3_1_0_slim_min_map = Url("jquery-3.1.0.slim.min.map");
    	public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
    	public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
    	public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
    	public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
    	public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
    	public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
	}

	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public static class Content {
		public const string UrlPath = "~/Content";
		public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
		public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
    	public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
    	public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
    	public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
    	public static readonly string bootstrap_theme_min_css_map = Url("bootstrap-theme.min.css.map");
    	public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
    	public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
    	public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
    	public static readonly string bootstrap_min_css_map = Url("bootstrap.min.css.map");
    	public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
	}

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class scripts 
        {
            public static class Assets
            {
                public const string ai_0_22_19_build00125_js = "~/scripts/ai.0.22.19-build00125.js"; 
                public const string ai_0_22_19_build00125_min_js = "~/scripts/ai.0.22.19-build00125.min.js"; 
                public const string bootstrap_js = "~/scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/scripts/bootstrap.min.js"; 
                public const string jquery_3_1_0_intellisense_js = "~/scripts/jquery-3.1.0.intellisense.js"; 
                public const string jquery_3_1_0_js = "~/scripts/jquery-3.1.0.js"; 
                public const string jquery_3_1_0_min_js = "~/scripts/jquery-3.1.0.min.js"; 
                public const string jquery_3_1_0_slim_js = "~/scripts/jquery-3.1.0.slim.js"; 
                public const string jquery_3_1_0_slim_min_js = "~/scripts/jquery-3.1.0.slim.min.js"; 
                public const string jquery_validate_js = "~/scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/scripts/jquery.validate.unobtrusive.min.js"; 
                public const string modernizr_2_8_3_js = "~/scripts/modernizr-2.8.3.js"; 
            }
        }
        public static partial class Content 
        {
            public static class Assets
            {
                public const string bootstrap_theme_css = "~/Content/bootstrap-theme.css";
                public const string bootstrap_theme_min_css = "~/Content/bootstrap-theme.min.css";
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string Site_css = "~/Content/Site.css";
            }
        }
	}
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


