//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Messages {
        
        /// <summary>
        ///   Looks up a localized string similar to: Values of the Fields {1} and {2} must be equal!
        /// </summary>
        public static string Compare(object arg1, object arg2, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.Compare, System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("Compare", resourceCulture), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} must be equal to {1}
        /// </summary>
        public static string Confirm(object arg0, object arg1, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.Confirm, System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("Confirm", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: از بانک اطلاعاتی با موفقيت فايل پشتيبان گرفته شد. 
        /// </summary>
        public static string DatabaseBackup([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.DatabaseBackup;
            }
            return global::Resources.Messages.ResourceManager.GetString("DatabaseBackup", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Display Messages
        /// </summary>
        public static string DisplayMessages([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.DisplayMessages;
            }
            return global::Resources.Messages.ResourceManager.GetString("DisplayMessages", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The {0} field value is already exist! Please choose another one.
        /// </summary>
        public static string DuplicateError(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.DuplicateError, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("DuplicateError", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: متاسفانه تا اين لحظه، نشانی پست الکترونيکی شما تاييد نشده است! لطفا برای تاييد آن، به صندوق پست الکترونيکی خود مراجعه نماييد.
        /// </summary>
        public static string Error002([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Error002;
            }
            return global::Resources.Messages.ResourceManager.GetString("Error002", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: متاسفانه شما قادر به ورود به پايگاه نمی‌باشيد! لطفا با مسوولين پايگاه تماس حاصل فرماييد.
        /// </summary>
        public static string Error003([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Error003;
            }
            return global::Resources.Messages.ResourceManager.GetString("Error003", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} صفحه از اين قالب استفاده می کند! لذا شما قادر به حذف آن نمی‌باشيد.
        /// </summary>
        public static string Error007(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.Error007, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("Error007", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: متاسفانه گذرواژه جاری را به درستی وارد نکرده ايد!
        /// </summary>
        public static string Error008([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Error008;
            }
            return global::Resources.Messages.ResourceManager.GetString("Error008", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: شناسه کاربری و/يا گذرواژه صحيح نمی باشد! لطفا مجددا سعی کنيد
        /// </summary>
        public static string Error009([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Error009;
            }
            return global::Resources.Messages.ResourceManager.GetString("Error009", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: You did not specify file for uploading!
        /// </summary>
        public static string Error100([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Error100;
            }
            return global::Resources.Messages.ResourceManager.GetString("Error100", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: از اين اطلاعات در جای ديگری استفاده شده است، لذا شما قادر به حذف آن نمی‌باشيد!
        /// </summary>
        public static string Error101([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Error101;
            }
            return global::Resources.Messages.ResourceManager.GetString("Error101", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The file is in use! So you can not delete it...
        /// </summary>
        public static string Error110([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Error110;
            }
            return global::Resources.Messages.ResourceManager.GetString("Error110", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Random Data Has Been Created Previously!
        /// </summary>
        public static string Error200([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Error200;
            }
            return global::Resources.Messages.ResourceManager.GetString("Error200", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Error on sending or receiving data!
        /// </summary>
        public static string ErrorOnJson([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.ErrorOnJson;
            }
            return global::Resources.Messages.ResourceManager.GetString("ErrorOnJson", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: گذرواژه جديد شما با موفقيت ثبت گرديد. 
        /// </summary>
        public static string Information001([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Information001;
            }
            return global::Resources.Messages.ResourceManager.GetString("Information001", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: اطلاعات شما با موفقيت ثبت گرديد.
        /// </summary>
        public static string Information002([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Information002;
            }
            return global::Resources.Messages.ResourceManager.GetString("Information002", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: عمليات به‌روزرسانی اطلاعات زيرسيستم‌ها، بخش‌ها و فعاليت‌ها با موفقيت انجام گرديد.
        /// </summary>
        public static string Information003([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Information003;
            }
            return global::Resources.Messages.ResourceManager.GetString("Information003", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: عکس شما با موفقيت ارسال گرديد
        /// </summary>
        public static string Information004([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Information004;
            }
            return global::Resources.Messages.ResourceManager.GetString("Information004", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: رزومه شما با موفقيت ارسال گرديد
        /// </summary>
        public static string Information005([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Information005;
            }
            return global::Resources.Messages.ResourceManager.GetString("Information005", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: فايل مربوطه در مدت {0} با موفقيت ذخيره گرديد.
        /// </summary>
        public static string Information006(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.Information006, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("Information006", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Random Data Created Successfully.
        /// </summary>
        public static string Information007([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Information007;
            }
            return global::Resources.Messages.ResourceManager.GetString("Information007", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The file uploaded successfully.
        /// </summary>
        public static string Information010([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Information010;
            }
            return global::Resources.Messages.ResourceManager.GetString("Information010", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The file deleted successfully.
        /// </summary>
        public static string Information011([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Information011;
            }
            return global::Resources.Messages.ResourceManager.GetString("Information011", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Error on sending/receiving Data!
        /// </summary>
        public static string JsonRequestError([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.JsonRequestError;
            }
            return global::Resources.Messages.ResourceManager.GetString("JsonRequestError", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Loading... Please Wait!
        /// </summary>
        public static string Loading([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Loading;
            }
            return global::Resources.Messages.ResourceManager.GetString("Loading", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Length of {0} could not be more than {1}!
        /// </summary>
        public static string MaxLength(object arg0, object arg1, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.MaxLength, System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("MaxLength", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Are you sure you want to delete this?
        /// </summary>
        public static string Question001([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Question001;
            }
            return global::Resources.Messages.ResourceManager.GetString("Question001", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} must be between {1} and {2}!
        /// </summary>
        public static string Range(object arg0, object arg1, object arg2, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.Range, System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("Range", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: You did not specify a valid cell phone number!
        /// </summary>
        public static string RegularExpressionForCellPhoneNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.RegularExpressionForCellPhoneNumber;
            }
            return global::Resources.Messages.ResourceManager.GetString("RegularExpressionForCellPhoneNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: For the field {0} you are just allowed to use integer or double numbers!
        /// </summary>
        public static string RegularExpressionForDouble(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForDouble, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForDouble", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} is not a valid email address!
        /// </summary>
        public static string RegularExpressionForEmail(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForEmail, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForEmail", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 1 - 100 characters.
        /// </summary>
        public static string RegularExpressionForFileName(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForFileName, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForFileName", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: For the field {0} you are just allowed to use integer numbers!
        /// </summary>
        public static string RegularExpressionForInteger(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForInteger, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForInteger", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} is not valid!
        /// </summary>
        public static string RegularExpressionForMoney(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForMoney, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForMoney", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} is invalid! {0} must contains 10 digits.
        /// </summary>
        public static string RegularExpressionForNationalCode(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForNationalCode, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForNationalCode", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 8 - 40 characters.
        /// </summary>
        public static string RegularExpressionForPassword(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForPassword, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForPassword", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: For the field {0} you should use numbers between 0.00 to 100.00!
        /// </summary>
        public static string RegularExpressionForPercentage(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForPercentage, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForPercentage", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} is not a valid url address!
        /// </summary>
        public static string RegularExpressionForUrl(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForUrl, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForUrl", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 6 - 20 characters.
        /// </summary>
        public static string RegularExpressionForUsername(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForUsername, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForUsername", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: For the field {0} you are just allowed to use integer numbers >=0
        /// </summary>
        public static string RegularExpressionForZeroOrUnsignedInteger(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionForZeroOrUnsignedInteger, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionForZeroOrUnsignedInteger", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The {0} is required!
        /// </summary>
        public static string Required(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.Required, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("Required", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Required!
        /// </summary>
        public static string RequiredGeneral([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.RequiredGeneral;
            }
            return global::Resources.Messages.ResourceManager.GetString("RequiredGeneral", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Your information saved successfully.
        /// </summary>
        public static string Save([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.Save;
            }
            return global::Resources.Messages.ResourceManager.GetString("Save", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Select an item...
        /// </summary>
        public static string SelectAnItem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.SelectAnItem;
            }
            return global::Resources.Messages.ResourceManager.GetString("SelectAnItem", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: {0} must be between {2} and {1} characters!
        /// </summary>
        public static string StringLength(object arg0, object arg2, object arg1, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.StringLength, System.Tuple.Create("0", arg0), System.Tuple.Create("2", arg2), System.Tuple.Create("1", arg1));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("StringLength", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("2", arg2), System.Tuple.Create("1", arg1));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: An unknown error has occurred! Please contact the system administrator.
        /// </summary>
        public static string UnexpectedError([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.UnexpectedError;
            }
            return global::Resources.Messages.ResourceManager.GetString("UnexpectedError", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: مقدار فيلد {0} معتبر نمی‌باشد!
        /// </summary>
        public static string UnvalidatedValue(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.UnvalidatedValue, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("UnvalidatedValue", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: You can select an item...
        /// </summary>
        public static string YouCanSelectAnItem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.YouCanSelectAnItem;
            }
            return global::Resources.Messages.ResourceManager.GetString("YouCanSelectAnItem", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: You should select an item!
        /// </summary>
        public static string YouShouldSelectAnItem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Messages.YouShouldSelectAnItem;
            }
            return global::Resources.Messages.ResourceManager.GetString("YouShouldSelectAnItem", resourceCulture);
        }
    }
}
namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MessagesKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Values of the Fields {1} and {2} must be equal!
        /// </summary>
        public const string Compare = "Compare";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} must be equal to {1}
        /// </summary>
        public const string Confirm = "Confirm";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: از بانک اطلاعاتی با موفقيت فايل پشتيبان گرفته شد. 
        /// </summary>
        public const string DatabaseBackup = "DatabaseBackup";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Display Messages
        /// </summary>
        public const string DisplayMessages = "DisplayMessages";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The {0} field value is already exist! Please choose another one.
        /// </summary>
        public const string DuplicateError = "DuplicateError";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: متاسفانه تا اين لحظه، نشانی پست الکترونيکی شما تاييد نشده است! لطفا برای تاييد آن، به صندوق پست الکترونيکی خود مراجعه نماييد.
        /// </summary>
        public const string Error002 = "Error002";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: متاسفانه شما قادر به ورود به پايگاه نمی‌باشيد! لطفا با مسوولين پايگاه تماس حاصل فرماييد.
        /// </summary>
        public const string Error003 = "Error003";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} صفحه از اين قالب استفاده می کند! لذا شما قادر به حذف آن نمی‌باشيد.
        /// </summary>
        public const string Error007 = "Error007";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: متاسفانه گذرواژه جاری را به درستی وارد نکرده ايد!
        /// </summary>
        public const string Error008 = "Error008";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: شناسه کاربری و/يا گذرواژه صحيح نمی باشد! لطفا مجددا سعی کنيد
        /// </summary>
        public const string Error009 = "Error009";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You did not specify file for uploading!
        /// </summary>
        public const string Error100 = "Error100";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: از اين اطلاعات در جای ديگری استفاده شده است، لذا شما قادر به حذف آن نمی‌باشيد!
        /// </summary>
        public const string Error101 = "Error101";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The file is in use! So you can not delete it...
        /// </summary>
        public const string Error110 = "Error110";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Random Data Has Been Created Previously!
        /// </summary>
        public const string Error200 = "Error200";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Error on sending or receiving data!
        /// </summary>
        public const string ErrorOnJson = "ErrorOnJson";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: گذرواژه جديد شما با موفقيت ثبت گرديد. 
        /// </summary>
        public const string Information001 = "Information001";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: اطلاعات شما با موفقيت ثبت گرديد.
        /// </summary>
        public const string Information002 = "Information002";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: عمليات به‌روزرسانی اطلاعات زيرسيستم‌ها، بخش‌ها و فعاليت‌ها با موفقيت انجام گرديد.
        /// </summary>
        public const string Information003 = "Information003";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: عکس شما با موفقيت ارسال گرديد
        /// </summary>
        public const string Information004 = "Information004";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: رزومه شما با موفقيت ارسال گرديد
        /// </summary>
        public const string Information005 = "Information005";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: فايل مربوطه در مدت {0} با موفقيت ذخيره گرديد.
        /// </summary>
        public const string Information006 = "Information006";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Random Data Created Successfully.
        /// </summary>
        public const string Information007 = "Information007";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The file uploaded successfully.
        /// </summary>
        public const string Information010 = "Information010";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The file deleted successfully.
        /// </summary>
        public const string Information011 = "Information011";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Error on sending/receiving Data!
        /// </summary>
        public const string JsonRequestError = "JsonRequestError";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Loading... Please Wait!
        /// </summary>
        public const string Loading = "Loading";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Length of {0} could not be more than {1}!
        /// </summary>
        public const string MaxLength = "MaxLength";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Are you sure you want to delete this?
        /// </summary>
        public const string Question001 = "Question001";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} must be between {1} and {2}!
        /// </summary>
        public const string Range = "Range";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You did not specify a valid cell phone number!
        /// </summary>
        public const string RegularExpressionForCellPhoneNumber = "RegularExpressionForCellPhoneNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: For the field {0} you are just allowed to use integer or double numbers!
        /// </summary>
        public const string RegularExpressionForDouble = "RegularExpressionForDouble";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} is not a valid email address!
        /// </summary>
        public const string RegularExpressionForEmail = "RegularExpressionForEmail";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 1 - 100 characters.
        /// </summary>
        public const string RegularExpressionForFileName = "RegularExpressionForFileName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: For the field {0} you are just allowed to use integer numbers!
        /// </summary>
        public const string RegularExpressionForInteger = "RegularExpressionForInteger";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} is not valid!
        /// </summary>
        public const string RegularExpressionForMoney = "RegularExpressionForMoney";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} is invalid! {0} must contains 10 digits.
        /// </summary>
        public const string RegularExpressionForNationalCode = "RegularExpressionForNationalCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 8 - 40 characters.
        /// </summary>
        public const string RegularExpressionForPassword = "RegularExpressionForPassword";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: For the field {0} you should use numbers between 0.00 to 100.00!
        /// </summary>
        public const string RegularExpressionForPercentage = "RegularExpressionForPercentage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} is not a valid url address!
        /// </summary>
        public const string RegularExpressionForUrl = "RegularExpressionForUrl";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 6 - 20 characters.
        /// </summary>
        public const string RegularExpressionForUsername = "RegularExpressionForUsername";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: For the field {0} you are just allowed to use integer numbers >=0
        /// </summary>
        public const string RegularExpressionForZeroOrUnsignedInteger = "RegularExpressionForZeroOrUnsignedInteger";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The {0} is required!
        /// </summary>
        public const string Required = "Required";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Required!
        /// </summary>
        public const string RequiredGeneral = "RequiredGeneral";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Your information saved successfully.
        /// </summary>
        public const string Save = "Save";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Select an item...
        /// </summary>
        public const string SelectAnItem = "SelectAnItem";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: {0} must be between {2} and {1} characters!
        /// </summary>
        public const string StringLength = "StringLength";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: An unknown error has occurred! Please contact the system administrator.
        /// </summary>
        public const string UnexpectedError = "UnexpectedError";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: مقدار فيلد {0} معتبر نمی‌باشد!
        /// </summary>
        public const string UnvalidatedValue = "UnvalidatedValue";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You can select an item...
        /// </summary>
        public const string YouCanSelectAnItem = "YouCanSelectAnItem";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You should select an item!
        /// </summary>
        public const string YouShouldSelectAnItem = "YouShouldSelectAnItem";
    }
}
