//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Models.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class General {
        
        /// <summary>
        ///   Looks up a localized string similar to: Code
        /// </summary>
        public static string Code([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Code;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Code", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: CultureLcid
        /// </summary>
        public static string CultureLcid([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.CultureLcid;
            }
            return global::Resources.Models.General.ResourceManager.GetString("CultureLcid", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Day
        /// </summary>
        public static string Day([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Day;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Day", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Description
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Description;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: First Name
        /// </summary>
        public static string FirstName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.FirstName;
            }
            return global::Resources.Models.General.ResourceManager.GetString("FirstName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Full Name
        /// </summary>
        public static string FullName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.FullName;
            }
            return global::Resources.Models.General.ResourceManager.GetString("FullName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Id
        /// </summary>
        public static string Id([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Id;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Id", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Active
        /// </summary>
        public static string IsActive([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.IsActive;
            }
            return global::Resources.Models.General.ResourceManager.GetString("IsActive", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Deleted
        /// </summary>
        public static string IsDeleted([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.IsDeleted;
            }
            return global::Resources.Models.General.ResourceManager.GetString("IsDeleted", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Inactive
        /// </summary>
        public static string IsInactive([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.IsInactive;
            }
            return global::Resources.Models.General.ResourceManager.GetString("IsInactive", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is System
        /// </summary>
        public static string IsSystem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.IsSystem;
            }
            return global::Resources.Models.General.ResourceManager.GetString("IsSystem", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Verified
        /// </summary>
        public static string IsVerified([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.IsVerified;
            }
            return global::Resources.Models.General.ResourceManager.GetString("IsVerified", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Last Name
        /// </summary>
        public static string LastName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.LastName;
            }
            return global::Resources.Models.General.ResourceManager.GetString("LastName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Master Data Code
        /// </summary>
        public static string MasterDataCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.MasterDataCode;
            }
            return global::Resources.Models.General.ResourceManager.GetString("MasterDataCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Month
        /// </summary>
        public static string Month([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Month;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Month", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Name;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Ordering
        /// </summary>
        public static string Ordering([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Ordering;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Ordering", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Title
        /// </summary>
        public static string Title([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Title;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Title", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Year
        /// </summary>
        public static string Year([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Year;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Year", resourceCulture);
        }
    }
}
namespace Resources.Models.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class GeneralKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Code
        /// </summary>
        public const string Code = "Code";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: CultureLcid
        /// </summary>
        public const string CultureLcid = "CultureLcid";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Day
        /// </summary>
        public const string Day = "Day";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Description
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: First Name
        /// </summary>
        public const string FirstName = "FirstName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Full Name
        /// </summary>
        public const string FullName = "FullName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Id
        /// </summary>
        public const string Id = "Id";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Active
        /// </summary>
        public const string IsActive = "IsActive";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Deleted
        /// </summary>
        public const string IsDeleted = "IsDeleted";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Inactive
        /// </summary>
        public const string IsInactive = "IsInactive";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is System
        /// </summary>
        public const string IsSystem = "IsSystem";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Verified
        /// </summary>
        public const string IsVerified = "IsVerified";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Last Name
        /// </summary>
        public const string LastName = "LastName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Master Data Code
        /// </summary>
        public const string MasterDataCode = "MasterDataCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Month
        /// </summary>
        public const string Month = "Month";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Ordering
        /// </summary>
        public const string Ordering = "Ordering";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Title
        /// </summary>
        public const string Title = "Title";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Year
        /// </summary>
        public const string Year = "Year";
    }
}
