//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Areas.Security.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Role {
        
        /// <summary>
        ///   Looks up a localized string similar to: Manage of Roles
        /// </summary>
        public static string ControllerName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Areas.Security.Role.ControllerName;
            }
            return global::Resources.Areas.Security.Role.ResourceManager.GetString("ControllerName", resourceCulture);
        }
    }
}
namespace Resources.Areas.Security.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class RoleKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Manage of Roles
        /// </summary>
        public const string ControllerName = "ControllerName";
    }
}
